pub mod commands;
pub mod protocol;

use crate::app::config::AppConfig;
use tauri::ipc::Invoke;
use crate::service::{
    book_group_service::BookGroupService, book_service::BookService,
    book_source_service::BookSourceService, json_document_service::JsonDocumentService,
    local_epub_book::LocalEpubBookService, local_txt_book::LocalTxtBookService,
    reading_stats_service::ReadingStatsService, update_service::UpdateService,
    user_service::UserService,
};
use std::sync::Arc;

#[derive(Clone)]
pub struct AppState {
    pub config: AppConfig,
    pub book_service: Arc<BookService>,
    pub book_source_service: Arc<BookSourceService>,
    pub user_service: Arc<UserService>,
    pub book_group_service: Arc<BookGroupService>,
    pub local_txt_book_service: Arc<LocalTxtBookService>,
    pub local_epub_book_service: Arc<LocalEpubBookService>,
    pub json_document_service: Arc<JsonDocumentService>,
    pub reading_stats_service: Arc<ReadingStatsService>,
    pub update_service: Arc<UpdateService>,
}

/// Every IPC command, registered by the desktop shell via `.invoke_handler(...)`.
pub fn invoke_handler() -> impl Fn(Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        commands::health,
        commands::book::search_book,
        commands::book::search_book_multi,
        commands::book::explore_book,
        commands::book::get_book_info,
        commands::book::get_chapter_list,
        commands::book::get_book_content,
        commands::book::delete_book_cache,
        commands::book::get_bookshelf,
        commands::book::upload_txt_book,
        commands::book::upload_epub_book,
        commands::book::save_book,
        commands::book::save_books,
        commands::book::set_book_source,
        commands::book::delete_book,
        commands::book::delete_books,
        commands::book::save_book_progress,
        commands::book::get_shelf_book,
        commands::book::get_shelf_book_with_cache_info,
        commands::book::get_invalid_book_sources,
        commands::book::cache_book_sse,
        commands::book::search_book_multi_sse,
        commands::book::search_book_source_sse,
        commands::book::get_available_book_source,
        commands::book::get_available_book_source_sse,
        commands::book::book_source_debug_sse,
        commands::book::get_txt_toc_rules,
        commands::book_group::get_book_groups,
        commands::book_group::save_book_group,
        commands::book_group::delete_book_group,
        commands::book_group::save_book_group_order,
        commands::book_group::save_book_group_id,
        commands::book_group::add_book_group_multi,
        commands::book_group::remove_book_group_multi,
        commands::book_source::save_book_source,
        commands::book_source::save_book_sources,
        commands::book_source::get_book_source,
        commands::book_source::get_book_sources,
        commands::book_source::get_default_book_source_owner,
        commands::book_source::pin_book_source,
        commands::book_source::unpin_book_source,
        commands::book_source::login_book_source,
        commands::book_source::get_explore_kinds,
        commands::book_source::test_book_sources,
        commands::book_source::delete_invalid_book_sources,
        commands::book_source::delete_book_source,
        commands::book_source::delete_book_sources,
        commands::book_source::delete_all_book_sources,
        commands::book_source::read_remote_source_file,
        commands::book_source::read_source_file,
        commands::book_source::set_as_default_book_sources,
        commands::bookmark::get_bookmarks,
        commands::bookmark::save_bookmark,
        commands::bookmark::save_bookmarks,
        commands::bookmark::delete_bookmark,
        commands::bookmark::delete_bookmarks,
        commands::debug::debug_source_step,
        commands::reading_stats::add_reading_stats,
        commands::reading_stats::get_reading_stats_daily,
        commands::reading_stats::get_reading_stats_summary,
        commands::reading_stats::get_reading_stats_by_book,
        commands::replace_rule::get_replace_rules,
        commands::replace_rule::save_replace_rule,
        commands::replace_rule::save_replace_rules,
        commands::replace_rule::delete_replace_rule,
        commands::replace_rule::delete_replace_rules,
        commands::rss::get_rss_sources,
        commands::rss::save_rss_source,
        commands::rss::save_rss_sources,
        commands::rss::delete_rss_source,
        commands::rss::delete_rss_sources,
        commands::rss::read_remote_rss_source_file,
        commands::rss::read_rss_source_file,
        commands::rss::get_rss_articles,
        commands::rss::get_rss_content,
        commands::speech::request_speech_audio,
        commands::update::get_version_update,
        commands::update::dismiss_version_update,
        commands::user::save_user_config,
        commands::user::get_user_config,
        commands::user::upload_file,
        commands::user::delete_file,
        commands::webdav::get_webdav_file_list,
        commands::webdav::get_webdav_file,
        commands::webdav::upload_file_to_webdav,
        commands::webdav::delete_webdav_file,
        commands::webdav::delete_webdav_file_list,
        commands::webdav::get_webdav_home,
        commands::webdav::open_webdav_folder,
    ]
}
